services:
  db:
    image: ankane/pgvector:latest
    container_name: prsense_postgres
    restart: always
    environment:
      POSTGRES_USER: prsense
      POSTGRES_PASSWORD: prsense
      POSTGRES_DB: prsense_dev
    ports:
      - "10000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: ankane/pgvector:latest
    container_name: prsense_postgres_test
    restart: always
    environment:
      POSTGRES_USER: prsense
      POSTGRES_PASSWORD: prsense
      POSTGRES_DB: prsense_test
    ports:
      - "10001:5432"
    tmpfs:
      - /var/lib/postgresql/data # ephemeral DB (fast tests)

volumes:
  postgres_data:
